# Generated by Django 4.1 on 2024-04-20 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('idVendors', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=45)),
                ('Address', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='VendorPO',
            fields=[
                ('Purchase_Order_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('PO_issuer_ID', models.IntegerField()),
                ('PO_approver_ID', models.IntegerField()),
                ('Date_issued', models.DateField()),
                ('Date_approved', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                ('Invoice_number', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('Invoice_date', models.DateField()),
                ('Description', models.CharField(max_length=45)),
                ('Quantity', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Purchase_Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.vendorpo')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.vendor')),
            ],
        ),
    ]
